covered_call_tickers:
  - NVDA
  - GOOGL 

cc_recommendation:
  min_strike_prices:
    NVDA: 250  # only show NVDA covered call strikes >= $250
    GOOGL: 340 # only show GOOGL covered call strikes >= $340

cash_secured_put_tickers:
  - TQQQ
  - AMD

output_dir: ./reports/prasanna
log_dir: ./logs/prasanna
cache_dir: ./cache/prasanna
